# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name/description of the debt (e.g., 'Personal Loan')",
                        max_length=255,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount of the debt",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount paid so far",
                        max_digits=12,
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Remaining balance (auto-calculated)",
                        max_digits=12,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(db_index=True, help_text="Due date of the debt"),
                ),
                (
                    "last_interest_accrual_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date when interest was accrued",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("defaulted", "Defaulted"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current status of the debt",
                        max_length=20,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Interest rate in percentage (e.g., 10.00 = 10%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "penalty_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Penalty rate in percentage (e.g., 2.00 = 2%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "interest_calculation_period",
                    models.CharField(
                        choices=[
                            ("per_annum", "Per Annum"),
                            ("per_month", "Per Month"),
                        ],
                        default="per_annum",
                        help_text="How interest is calculated (per annum or per month)",
                        max_length=20,
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        help_text="Borrower who owns this debt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts",
                        to="borrowers.borrower",
                    ),
                ),
            ],
            options={
                "verbose_name": "Debt",
                "verbose_name_plural": "Debts",
                "db_table": "debts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForgivenessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount_forgiven",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount forgiven",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "previous_total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount before forgiveness",
                        max_digits=12,
                    ),
                ),
                (
                    "new_total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount after forgiveness",
                        max_digits=12,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for forgiveness", null=True
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="User who created the forgiveness request",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        help_text="Approval status",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        help_text="User who approved the forgiveness",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the forgiveness was approved",
                        null=True,
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        help_text="Borrower who owns the debt (denormalized for faster queries)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forgiveness_logs",
                        to="borrowers.borrower",
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        help_text="Debt being forgiven",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forgiveness_logs",
                        to="debts.debt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forgiveness Log",
                "verbose_name_plural": "Forgiveness Logs",
                "db_table": "forgiveness_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterestRateChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "setting_key",
                    models.CharField(
                        db_index=True,
                        help_text="Which rate was changed (e.g., 'default_interest_rate' or 'loan_123')",
                        max_length=100,
                    ),
                ),
                (
                    "old_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous rate value",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="New rate value",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        default="system",
                        help_text="User who changed the rate",
                        max_length=255,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the change", null=True
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the change was made"
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific loan this change applies to (null = system-wide)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interest_rate_changes",
                        to="debts.debt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interest Rate Change Log",
                "verbose_name_plural": "Interest Rate Change Logs",
                "db_table": "interest_rate_change_logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["borrower", "status"], name="debts_borrowe_d3dfd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["due_date", "status"], name="debts_due_dat_b47db5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(fields=["deleted_at"], name="debts_deleted_c2fc6d_idx"),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(fields=["status"], name="debts_status_f3b388_idx"),
        ),
        migrations.AddIndex(
            model_name="forgivenesslog",
            index=models.Index(
                fields=["borrower"], name="forgiveness_borrowe_d844b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forgivenesslog",
            index=models.Index(
                fields=["created_at"], name="forgiveness_created_ca5953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forgivenesslog",
            index=models.Index(fields=["status"], name="forgiveness_status_653d4f_idx"),
        ),
        migrations.AddIndex(
            model_name="forgivenesslog",
            index=models.Index(
                fields=["debt", "status"], name="forgiveness_debt_id_d1e78e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interestratechangelog",
            index=models.Index(
                fields=["setting_key"], name="interest_ra_setting_5e72b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interestratechangelog",
            index=models.Index(
                fields=["changed_by"], name="interest_ra_changed_74d281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interestratechangelog",
            index=models.Index(
                fields=["changed_at"], name="interest_ra_changed_aa86d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interestratechangelog",
            index=models.Index(fields=["loan"], name="interest_ra_loan_id_1bd216_idx"),
        ),
    ]
