# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("debts", "0001_initial"),
        ("payment_methods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PenaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Penalty amount", max_digits=12
                    ),
                ),
                (
                    "penalty_date",
                    models.DateField(
                        db_index=True, help_text="Date when penalty was applied"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for the penalty (e.g., 'Late payment')",
                        null=True,
                    ),
                ),
                (
                    "is_auto",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this penalty was auto-generated by the system",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penalty Transaction",
                "verbose_name_plural": "Penalty Transactions",
                "db_table": "penalty_transactions",
                "ordering": ["-penalty_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount paid", max_digits=12
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        db_index=True, help_text="Date when payment was made"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference number (e.g., transaction ID, check number)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the payment",
                        null=True,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the payment was recorded in the system",
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        help_text="Debt being paid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="debts.debt",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        help_text="Payment method used (Cash, Bank Transfer, GCash, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payment_methods.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "db_table": "payment_transactions",
                "ordering": ["-payment_date"],
            },
        ),
    ]
