# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("debts", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who recorded the payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="penaltytransaction",
            name="debt",
            field=models.ForeignKey(
                help_text="Debt being penalized",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="penalties",
                to="debts.debt",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["debt", "-payment_date"], name="payment_tra_debt_id_15c1ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment_date"], name="payment_tra_payment_4be022_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["reference"], name="payment_tra_referen_451c50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["deleted_at"], name="payment_tra_deleted_daf62f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["method"], name="payment_tra_method__22fe4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="penaltytransaction",
            index=models.Index(
                fields=["debt", "-penalty_date"], name="penalty_tra_debt_id_97f0b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="penaltytransaction",
            index=models.Index(
                fields=["penalty_date"], name="penalty_tra_penalty_3f10f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="penaltytransaction",
            index=models.Index(
                fields=["deleted_at"], name="penalty_tra_deleted_ac3377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="penaltytransaction",
            index=models.Index(
                fields=["is_auto"], name="penalty_tra_is_auto_84db78_idx"
            ),
        ),
    ]
