# Generated by Django 5.2.3 on 2026-07-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
