# Generated by Django 5.2.3 on 2026-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_paymenttransaction_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="penaltytransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("collected", "Collected"),
                    ("waived", "Waived"),
                    ("reversed", "Reversed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
