# Generated by Django 5.2.3 on 2025-12-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("update_profile", "Update Profile"),
                    ("change_role", "Change Role"),
                    ("delete_user", "Delete User"),
                    ("create_user", "Create User"),
                    ("reset_password", "Reset Password"),
                    ("deactivate_user", "Deactivate User"),
                    ("reactivate_user", "Reactivate User"),
                    ("view_logs", "View Logs"),
                ],
                max_length=50,
            ),
        ),
    ]
