# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of payment method (e.g., 'Cash', 'Bank Transfer')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the payment method",
                        null=True,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="CreditCard",
                        help_text="Icon name (for UI)",
                        max_length=50,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the default payment method",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "payment_methods",
                "ordering": ["-is_default", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="payment_met_name_8901d6_idx"),
                    models.Index(
                        fields=["is_default"], name="payment_met_is_defa_11be74_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="payment_met_deleted_50339c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethodStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of transactions using this method",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount processed using this method",
                        max_digits=12,
                    ),
                ),
                (
                    "method",
                    models.OneToOneField(
                        help_text="Payment method these stats belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="payment_methods.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method Stat",
                "verbose_name_plural": "Payment Method Stats",
                "db_table": "payment_method_stats",
            },
        ),
    ]
