version: '3.8'

services:
  db:
    container_name: collectly_db
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - collectly_net

  redis:
    image: redis:7-alpine
    container_name: collectly_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - collectly_net


  web:
    build: .
    container_name: collectly_web
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
      - shared_temp:/shared_temp
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - collectly_net

  celery:
    build: .
    container_name: collectly_celery
    command: celery -A core worker --loglevel=info --concurrency=4 --without-gossip --without-mingle --without-heartbeat
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - collectly_net

  celery-beat:
    build: .
    container_name: collectly_celery_beat
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
      - shared_temp:/shared_temp
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - collectly_net

volumes:
  postgres_data:
  redis_data:
  shared_temp:
  static_data:
  media_data:

networks:
  collectly_net:
    driver: bridge
