# Generated by Django 5.2.3 on 2026-07-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.CharField(
                        db_index=True,
                        help_text="Entity name (e.g., 'Borrower', 'Debt')",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(
                        help_text="ID of the record with conflict"
                    ),
                ),
                (
                    "local_data",
                    models.JSONField(
                        blank=True,
                        help_text="Local (client) version of the record",
                        null=True,
                    ),
                ),
                (
                    "server_data",
                    models.JSONField(
                        blank=True, help_text="Server version of the record", null=True
                    ),
                ),
                (
                    "merged_data",
                    models.JSONField(
                        blank=True,
                        help_text="Merged version (if resolved as merged)",
                        null=True,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("local", "Local (Use client data)"),
                            ("server", "Server (Use server data)"),
                            ("manual", "Manual"),
                            ("merged", "Merged"),
                        ],
                        default="pending",
                        help_text="How the conflict was resolved",
                        max_length=20,
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(
                        blank=True,
                        help_text="User who resolved the conflict",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the conflict was resolved",
                        null=True,
                    ),
                ),
                (
                    "local_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Local record's updated_at timestamp",
                        null=True,
                    ),
                ),
                (
                    "server_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Server record's updated_at timestamp",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the conflict",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Conflict",
                "verbose_name_plural": "Sync Conflicts",
                "db_table": "sync_conflicts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "entity_id"], name="idx_sync_conflict_entity"
                    ),
                    models.Index(
                        fields=["resolution"], name="idx_sync_conflict_resolution"
                    ),
                    models.Index(
                        fields=["created_at"], name="idx_sync_conflict_created"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="idx_sync_conflict_deleted"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.CharField(
                        db_index=True,
                        help_text="Entity name (e.g., 'Borrower', 'Debt', 'PaymentTransaction')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful sync timestamp",
                        null=True,
                    ),
                ),
                (
                    "last_sync_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of records synced in last sync"
                    ),
                ),
                (
                    "total_synced",
                    models.PositiveIntegerField(
                        default=0, help_text="Total records synced since beginning"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("syncing", "Syncing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        help_text="Sync status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Last error message if sync failed",
                        null=True,
                    ),
                ),
                (
                    "last_sync_started_at",
                    models.DateTimeField(
                        blank=True, help_text="When the last sync started", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Metadata",
                "verbose_name_plural": "Sync Metadata",
                "db_table": "sync_metadata",
                "ordering": ["entity"],
                "indexes": [
                    models.Index(fields=["entity"], name="idx_sync_meta_entity"),
                    models.Index(fields=["status"], name="idx_sync_meta_status"),
                    models.Index(
                        fields=["last_synced_at"], name="idx_sync_meta_last_synced"
                    ),
                    models.Index(fields=["deleted_at"], name="idx_sync_meta_deleted"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.CharField(
                        db_index=True,
                        help_text="Entity name (e.g., 'Borrower', 'Debt')",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(help_text="ID of the record"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        help_text="Action to perform",
                        max_length=20,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="Record data for create/update actions",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Queue status",
                        max_length=20,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=5, help_text="Maximum retry attempts"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Last error message", null=True
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this item was processed", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Queue",
                "verbose_name_plural": "Sync Queue",
                "db_table": "sync_queue",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "entity_id"], name="idx_sync_queue_entity"
                    ),
                    models.Index(fields=["status"], name="idx_sync_queue_status"),
                    models.Index(fields=["created_at"], name="idx_sync_queue_created"),
                    models.Index(fields=["deleted_at"], name="idx_sync_queue_deleted"),
                ],
            },
        ),
    ]
