# Generated by Django 5.2.3 on 2026-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique task identifier (UUID)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        help_text="Entity being synced (e.g., 'Borrower')",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Current status of the task",
                        max_length=20,
                    ),
                ),
                (
                    "total",
                    models.IntegerField(
                        default=0, help_text="Total number of records to process"
                    ),
                ),
                (
                    "processed",
                    models.IntegerField(
                        default=0, help_text="Number of records processed so far"
                    ),
                ),
                (
                    "failed",
                    models.IntegerField(
                        default=0, help_text="Number of records that failed"
                    ),
                ),
                (
                    "current_entity",
                    models.CharField(
                        blank=True,
                        help_text="Optional sub‑entity currently being processed",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Final results (created, updated, conflicts, etc.)",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the task failed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the task was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the task was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Progress",
                "verbose_name_plural": "Task Progresses",
                "db_table": "sync_task_progress",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_id"], name="sync_task_p_task_id_439aeb_idx"
                    ),
                    models.Index(
                        fields=["status"], name="sync_task_p_status_193507_idx"
                    ),
                    models.Index(
                        fields=["entity"], name="sync_task_p_entity_9abada_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="sync_task_p_created_b18302_idx"
                    ),
                ],
            },
        ),
    ]
