# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("debts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("signed", "Signed")],
                        default="draft",
                        help_text="Agreement status (draft or signed)",
                        max_length=10,
                    ),
                ),
                (
                    "agreement_date",
                    models.DateField(
                        blank=True, help_text="Date of the agreement", null=True
                    ),
                ),
                (
                    "lender_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the lender",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "terms_text",
                    models.TextField(
                        blank=True,
                        help_text="Full terms and conditions text",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded agreement file (PDF/DOCX)",
                        null=True,
                        upload_to="agreements/%Y/%m/",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the agreement was signed", null=True
                    ),
                ),
                (
                    "signed_by",
                    models.CharField(
                        blank=True,
                        help_text="Who signed the agreement",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Principal amount at signing",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Interest rate at signing",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "penalty_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Penalty rate at signing",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Due date at signing", null=True
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True, help_text="Loan purpose", max_length=255, null=True
                    ),
                ),
                (
                    "loan_start_date",
                    models.DateField(
                        blank=True, help_text="Loan start date", null=True
                    ),
                ),
                (
                    "anniversary_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Day of month for anniversary (1-31)",
                        null=True,
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        help_text="Debt associated with this agreement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="debts.debt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Agreement",
                "verbose_name_plural": "Loan Agreements",
                "db_table": "loan_agreements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["debt", "status"], name="loan_agreem_debt_id_7b0a9a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="loan_agreem_status_925c96_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="loan_agreem_deleted_60d0f3_idx"
                    ),
                ],
            },
        ),
    ]
