from django.db import models
from core.models.baseModel import BaseModel
from debts.models.debt import Debt


class PenaltyStatus(models.TextChoices):
    PENDING = "pending", "Pending"
    COLLECTED = "collected", "Collected"
    WAIVED = "waived", "Waived"
    REVERSED = "reversed", "Reversed"


class PenaltyTransaction(BaseModel):
    """
    Penalty transaction record for a debt.
    Tracks penalties applied to overdue debts.
    """

    debt = models.ForeignKey(
        Debt,
        on_delete=models.CASCADE,
        related_name="penalties",
        help_text="Debt being penalized",
    )

    amount = models.DecimalField(
        max_digits=12, decimal_places=2, help_text="Penalty amount"
    )
    penalty_date = models.DateField(
        db_index=True, help_text="Date when penalty was applied"
    )
    status = models.CharField(
        choices=PenaltyStatus.choices,
        default=PenaltyStatus.PENDING,
        db_index=True,
        max_length=20,
    )
    reason = models.TextField(
        null=True, blank=True, help_text="Reason for the penalty (e.g., 'Late payment')"
    )

    is_auto = models.BooleanField(
        default=False, help_text="Whether this penalty was auto-generated by the system"
    )

    class Meta:
        db_table = "penalty_transactions"
        ordering = ["-penalty_date"]
        indexes = [
            models.Index(fields=["debt", "-penalty_date"]),
            models.Index(fields=["penalty_date"]),
            models.Index(fields=["deleted_at"]),
            models.Index(fields=["is_auto"]),
        ]
        verbose_name = "Penalty Transaction"
        verbose_name_plural = "Penalty Transactions"

    def __str__(self):
        return f"Penalty #{self.id} - {self.debt.name} - {self.amount_display}"

    @property
    def amount_display(self):
        return f"₱{self.amount:,.2f}"

    @property
    def is_void(self):
        """Check if penalty has been voided (soft-deleted)."""
        return self.deleted_at is not None

    def save(self, *args, **kwargs):
        """Auto-update debt remaining_amount on save."""
        super().save(*args, **kwargs)
        # Update debt remaining amount
        if self.debt:
            self.debt.remaining_amount = self.debt.total_amount - self.debt.paid_amount
            self.debt.save()
