# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "debtor_name",
                    models.CharField(
                        help_text="Borrower's full name (snapshot)", max_length=255
                    ),
                ),
                (
                    "debtor_contact",
                    models.CharField(
                        blank=True,
                        help_text="Borrower's contact (snapshot)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "debtor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Borrower's email (snapshot)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "debtor_address",
                    models.TextField(
                        blank=True, help_text="Borrower's address (snapshot)", null=True
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount requested", max_digits=12
                    ),
                ),
                (
                    "purpose",
                    models.CharField(help_text="Purpose of the loan", max_length=255),
                ),
                ("proposed_due_date", models.DateField(help_text="Proposed due date")),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Proposed interest rate",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Application status",
                        max_length=10,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the application was approved",
                        null=True,
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the application was rejected",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        help_text="Who approved the application",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection", null=True
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Existing borrower (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_applications",
                        to="borrowers.borrower",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Application",
                "verbose_name_plural": "Loan Applications",
                "db_table": "loan_applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="loan_applic_status_2fc934_idx"
                    ),
                    models.Index(
                        fields=["debtor", "status"],
                        name="loan_applic_debtor__00146b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="loan_applic_created_15dc53_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="loan_applic_deleted_b92902_idx"
                    ),
                ],
            },
        ),
    ]
