# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("partial_update", "Partial Update"),
                            ("delete", "Delete"),
                            ("read", "Read"),
                            ("read_stats", "Read Stats"),
                            ("status_change", "Status Change"),
                            ("stats_read", "Stats Read"),
                            ("read_grouped_config", "Read Grouped Config"),
                            ("read_system_info", "Read System Info"),
                            ("update_grouped_config", "Update Grouped Config"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("logout_all", "Logout All"),
                            ("login_failed", "Login Failed"),
                            ("session_terminate", "Session Terminate"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                            ("user_create", "User Create"),
                            ("user_update", "User Update"),
                            ("user_delete", "User Delete"),
                            ("role_assign", "Role Assign"),
                            ("role_revoke", "Role Revoke"),
                            ("permission_update", "Permission Update"),
                            ("config_update", "Config Update"),
                            ("settings_change", "Settings Change"),
                            ("feature_toggle", "Feature Toggle"),
                            ("notification_error", "Notification Error"),
                            ("notification_update", "Notification Update"),
                            ("notification_delete", "Notification Delete"),
                            ("activation_error", "Activation Error"),
                            ("activation_create", "Activation Create"),
                            ("activation_update", "Activation Update"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("system_alert", "System Alert"),
                            ("audit_export", "Audit Export"),
                            ("2fa_initiated", "2 factor Initiated"),
                            ("debt_create", "Debt Create"),
                            ("debt_update", "Debt Update"),
                            ("debt_delete", "Debt Delete"),
                            ("debt_forgive", "Debt Forgiveness"),
                            ("payment_create", "Payment Create"),
                            ("payment_update", "Payment Update"),
                            ("payment_delete", "Payment Delete"),
                            ("penalty_create", "Penalty Create"),
                            ("penalty_update", "Penalty Update"),
                            ("penalty_delete", "Penalty Delete"),
                            ("borrower_create", "Borrower Create"),
                            ("borrower_update", "Borrower Update"),
                            ("borrower_delete", "Borrower Delete"),
                            ("loan_agreement_create", "Loan Agreement Create"),
                            ("loan_agreement_signed", "Loan Agreement Signed"),
                            ("loan_application_create", "Loan Application Create"),
                            ("loan_application_approved", "Loan Application Approved"),
                            ("loan_application_rejected", "Loan Application Rejected"),
                            ("group_create", "Group Create"),
                            ("group_update", "Group Update"),
                            ("group_delete", "Group Delete"),
                            ("group_member_add", "Group Member Add"),
                            ("group_member_remove", "Group Member Remove"),
                            ("payment_method_create", "Payment Method Create"),
                            ("payment_method_update", "Payment Method Update"),
                            ("payment_method_delete", "Payment Method Delete"),
                            ("credit_check_performed", "Credit Check Performed"),
                            ("interest_rate_change", "Interest Rate Change"),
                            ("sync_pull", "Sync Pull"),
                            ("sync_push", "Sync Push"),
                            ("print_receipt", "Print Receipt"),
                            ("export_data", "Export Data"),
                            ("import_data", "Import Data"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("is_suspicious", models.BooleanField(default=False)),
                (
                    "suspicious_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retention_years", models.IntegerField(default=5)),
                ("immutable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
