# Generated by Django 5.2.3 on 2026-07-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0007_alter_auditlog_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditpolicy",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("draft", "Draft"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
