# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borrower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Full name of the borrower",
                        max_length=255,
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Phone number or contact details",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address (must be unique)",
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Physical address", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the borrower",
                        null=True,
                    ),
                ),
                (
                    "credit_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Poor", "Poor"),
                        ],
                        help_text="Credit rating based on latest credit check",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Borrower",
                "verbose_name_plural": "Borrowers",
                "db_table": "borrowers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CreditCheckLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Credit score (300-850 range)",
                        validators=[
                            django.core.validators.MinValueValidator(
                                300, message="Score must be at least 300"
                            ),
                            django.core.validators.MaxValueValidator(
                                850, message="Score must be at most 850"
                            ),
                        ],
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        help_text="Risk level based on score",
                        max_length=10,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Additional remarks about the credit check",
                        null=True,
                    ),
                ),
                (
                    "date_checked",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the credit check was performed",
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID from external credit bureau",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Check Log",
                "verbose_name_plural": "Credit Check Logs",
                "db_table": "credit_check_logs",
                "ordering": ["-date_checked"],
            },
        ),
    ]
