# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="borrower",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated system user account (if borrower has login access)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="borrower_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creditchecklog",
            name="debtor",
            field=models.ForeignKey(
                help_text="Borrower being checked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_checks",
                to="borrowers.borrower",
            ),
        ),
        migrations.AddField(
            model_name="creditchecklog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the credit check",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_checks_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="borrower",
            index=models.Index(fields=["name"], name="borrowers_name_5ace6d_idx"),
        ),
        migrations.AddIndex(
            model_name="borrower",
            index=models.Index(fields=["email"], name="borrowers_email_066745_idx"),
        ),
        migrations.AddIndex(
            model_name="borrower",
            index=models.Index(fields=["contact"], name="borrowers_contact_9e71d2_idx"),
        ),
        migrations.AddIndex(
            model_name="borrower",
            index=models.Index(
                fields=["deleted_at"], name="borrowers_deleted_937a5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditchecklog",
            index=models.Index(
                fields=["debtor", "-date_checked"],
                name="credit_chec_debtor__506f5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creditchecklog",
            index=models.Index(
                fields=["risk_level"], name="credit_chec_risk_le_158925_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditchecklog",
            index=models.Index(
                fields=["date_checked"], name="credit_chec_date_ch_ef7707_idx"
            ),
        ),
    ]
