# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the group (e.g., 'VIP', 'High-Risk')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the group", null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex color code for the group (e.g., '#3b82f6')",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Debtor Group",
                "verbose_name_plural": "Debtor Groups",
                "db_table": "debtor_groups",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="debtor_grou_name_6cc3f4_idx"),
                    models.Index(
                        fields=["deleted_at"], name="debtor_grou_deleted_15d16c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DebtorGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the borrower was assigned to the group",
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        help_text="Borrower who is a member of the group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="borrowers.borrower",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group that the borrower belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="groups.debtorgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Debtor Group Member",
                "verbose_name_plural": "Debtor Group Members",
                "db_table": "debtor_group_members",
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["group", "debtor"],
                        name="debtor_grou_group_i_80d1d3_idx",
                    ),
                    models.Index(
                        fields=["debtor"], name="debtor_grou_debtor__b545b0_idx"
                    ),
                    models.Index(
                        fields=["group"], name="debtor_grou_group_i_2196cd_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="debtor_grou_deleted_097b81_idx"
                    ),
                ],
                "unique_together": {("group", "debtor")},
            },
        ),
    ]
