# Generated by Django 5.2.3 on 2026-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Setting key (e.g., 'company_name', 'default_interest_rate')",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Setting value (stored as text, parsed when needed)"
                    ),
                ),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("collections", "Collections"),
                            ("loans", "Loans"),
                            ("notifications", "Notifications"),
                            ("reports", "Reports"),
                            ("integrations", "Integrations"),
                            ("audit_security", "Audit & Security"),
                        ],
                        db_index=True,
                        help_text="Category of the setting",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this setting does",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this setting is publicly readable",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
                "ordering": ["setting_type", "key"],
                "indexes": [
                    models.Index(
                        fields=["setting_type", "key"],
                        name="system_sett_setting_bf58a2_idx",
                    ),
                    models.Index(
                        fields=["is_public"], name="system_sett_is_publ_c2e919_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="system_sett_deleted_822620_idx"
                    ),
                ],
                "unique_together": {("setting_type", "key")},
            },
        ),
    ]
