# Generated by Django 5.2.3 on 2026-06-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("debts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient_email",
                    models.EmailField(
                        help_text="Recipient email address", max_length=254
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Email subject", max_length=255, null=True
                    ),
                ),
                (
                    "payload",
                    models.TextField(
                        blank=True,
                        help_text="Message content (HTML or text)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("resend", "Resend"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if delivery failed",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "resend_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of manual resend attempts"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was successfully sent",
                        null=True,
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, help_text="When the last error occurred", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="notificatio_status_95b675_idx"
                    ),
                    models.Index(
                        fields=["recipient_email"],
                        name="notificatio_recipie_20e31c_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="notificatio_status_e36129_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_45a1e0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=255),
                ),
                ("message", models.TextField(help_text="Notification message")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("info", "Info"),
                            ("reminder", "Reminder"),
                            ("overdue", "Overdue"),
                            ("payment_confirmation", "Payment Confirmation"),
                        ],
                        default="reminder",
                        help_text="Notification type",
                        max_length=20,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification should be sent",
                        null=True,
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related debt (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="debts.debt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_read"], name="notificatio_is_read_3f8c44_idx"
                    ),
                    models.Index(
                        fields=["scheduled_for"], name="notificatio_schedul_3d00b6_idx"
                    ),
                    models.Index(
                        fields=["debt", "is_read"],
                        name="notificatio_debt_id_ab3069_idx",
                    ),
                    models.Index(fields=["type"], name="notificatio_type_8a8a78_idx"),
                    models.Index(
                        fields=["deleted_at"], name="notificatio_deleted_3186d3_idx"
                    ),
                ],
            },
        ),
    ]
