# Generated by Django 5.2.3 on 2026-07-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="channel",
            field=models.CharField(
                choices=[("email", "Email"), ("sms", "SMS")],
                db_index=True,
                default="email",
                help_text="Delivery channel",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="recipient",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Email address or phone number",
                max_length=255,
                null=True,
            ),
        ),
    ]
