# Generated by Django 5.2.3 on 2026-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationlog_channel_notificationlog_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="recipient_email",
            field=models.EmailField(
                blank=True,
                help_text="Recipient email address",
                max_length=254,
                null=True,
            ),
        ),
    ]
